### ISSUE TITLE
GoogleApiAvailability() doesn't have a default constructor

### ISSUE THREAD

**Issue by kari538** [Baseflow/flutter-google-api-availability#20]
## 🐛 Bug Report

I copy-past this line of code from your package Readme page:

`GooglePlayServicesAvailability availability = await GoogleApiAvailability().checkGooglePlayServicesAvailability();`

But I immediately get the error:

`The class 'GoogleApiAvailability' doesn't have a default constructor.  Try using one of the named constructors defined in 'GoogleApiAvailability'.`

**Version:** 2.0.4

**Platform:** 
- [ ] :robot: Android

**Comment by wenxiangjiang** [comment]
Please use `GoogleApiAvailability.instance` instead.

**Comment by mvanbeusekom** [comment]
I have updated the documentation to reflect using the `GoogleApiAvailability.instance` accessor.

**Comment by kari538** [comment]
Awesome! 👍🏻 Nice job.

**Comment by mvanbeusekom** [comment]
Sorry for being so incredibly late ;), I completely missed you created the issue.

**Comment by kari538** [comment]
Oh, that's ok, I solved it by trial-and-error a long time ago! 😄

But it feels satisfying to know that the documentation is now up to date. 😉 For future users.
