### ISSUE TITLE
Support null safety

### ISSUE THREAD

**Issue by IchordeDionysos** [Baseflow/flutter-google-api-availability#22]
## 🚀 Feature Requests

This is a request to add support for [null safety](https://dart.dev/null-safety) to `package:google_api_availability`.
We depend on your awesome package, so would be great to have null safety enabled.

### Contextualize the feature

The Dart/Flutter team already encourages publishing the migrated packages: See [this blog post](https://medium.com/dartlang/preparing-the-dart-and-flutter-ecosystem-for-null-safety-e550ce72c010).

### Describe the feature

See the [migration guide](https://dart.dev/null-safety/migration-guide) for details about enabling null safety.

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi @IchordeDionysos, 

Thank you for raising this issue. I have just release version 3.0.0 of the [google_api_availability](https://pub.dev/packages/google_api_availability/versions/3.0.0) plugin which is null safe.

**Comment by IchordeDionysos** [comment]
Wow @mvanbeusekom thanks for you extremely quick response 😍

I am impressed 💪
