### ISSUE TITLE
Return Play Services version

### ISSUE THREAD

**Issue by venzeo** [Baseflow/flutter-google-api-availability#25]
## 🚀 Feature Requests
Would it be possible for you to also return a version of Google Play Services running on the device? This info is needed in order to prompt the user to update it in case it does not support needed functionality.

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by JDDV** [comment]
Hi @venzeo, this functionality is already built-in, but it's a bit hidden.
take a look [here](https://developers.google.com/android/reference/com/google/android/gms/common/GoogleApiAvailability.html#public-static-final-int-google_play_services_version_code) at the documentation.

If you have that line in the manifest and then call `checkPlayServicesAvailability` (which uses [isGooglePlayServicesAvailable](https://developers.google.com/android/reference/com/google/android/gms/common/GoogleApiAvailability#public-int-isgoogleplayservicesavailable-context-context)) you should get the correct connection status error code back.

The documentation says:

Verifies that Google Play services is installed and enabled on this device, **and that the version installed on this device is no older than the one required by this client.**

I will close this issue for now, if you still have questions feel free to ask me!

**Comment by sarbogast** [comment]
@JDDV Could you please clarify what line needs to be address to AndroidManifest.xml to specify the minimum version of Google Play Services my app requires?
