### ISSUE TITLE
Remove usage of jCenter

### ISSUE THREAD

**Issue by ueman** [Baseflow/flutter-google-api-availability#28]
## 🐛 Bug Report

This library still uses jCenter. jCenter doesn't get any updates anymore and should therefor be switched to mavenCentral.

See also https://developer.android.com/studio/build/jcenter-migration

### Expected behavior

No dependencies on jCenter

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by JDDV** [comment]
Hi @ueman, in version 3.0.2. it's updated and it uses now mavenCentral.
Thank you for bringing this to our attention!
