### ISSUE TITLE
Please return support IOS platform

### ISSUE THREAD

**Issue by postflow** [Baseflow/flutter-google-api-availability#45]
I use this library in common Dart code on two platforms and after upgrading to 5.0.0 in runtime there is an error 
### Platforms affected (mark all that apply)
- [x ] :iphone: iOS
- [ ] :robot: Android

**Comment by JeroenWeener** [comment]
Hi @postflow, thank you for reaching out. We decided to discontinue support for iOS, as the package never actually did anything there. As Google Play Services only exist on the Android platform, it does not make sense to claim iOS support.

As version 5.0.0, the support has been removed, causing the runtime error in your application. To fix it, you should probably wrap your code that is calling methods from this plugin in an if-statement to check whether the application is being run on Android.

```dart
if (Platform.isAndroid) {
    ...
}
```

Don't hesitate to comment if this change does not work for you or you have any other questions.

**Comment by TimHoogstrate** [comment]
This issues seems to be solved. Please feel free to reopen the issue if you have any additional information.
